# Generated by Django 3.2 on 2021-07-03 23:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Description', models.TextField(blank=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('review', 'Review'), ('published', 'Published')], default='review', max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.options')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
