# Generated by Django 3.2 on 2021-07-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='furnished',
        ),
        migrations.AddField(
            model_name='house',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
    ]
