# Generated by Django 3.2 on 2021-07-04 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_publishedmanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='Description',
            new_name='description',
        ),
    ]
