# Generated by Django 3.2 on 2021-07-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_description_house_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
